### PR TITLE
Correct a instruction generating function

### PR DESCRIPTION
**Pull request by hz0ne**
Here is a instruction generating function of U type, the release version missing a Bit extraction for `imm(i)`.

### CODE REVIEW

**Comment by chick** [comment]
This looks ok. Two questions
-  Is it possible to make a unit test that demonstrates that the fix works properly
- Shouldn't this change be applied to `master` first then be merged into `release`. It's minor but it looks like `master` is a commit ahead of `release`

**Comment by chick** [comment]
This looks ok. Questions
-  Is it possible to make a unit test that demonstrates that the fix works properly
- Your tests are failing because the `.install_verilator.sh` seems out of date. I just pushed a new one to branch `master` you should be able to use that.
- Just wanted to make sure that `release` is your intended target. `release` and `master` are diverging it would be nice to bring them back together, but I imagine that is beyond your scope. 
- Cheers

**Comment by jackkoenig** [comment]
@chick note that Travis open-source credits are super limited now, might be worth migrating to Github Actions

**Comment by dhxsy1994** [comment]
> This looks ok. Questions
> 
> * Is it possible to make a unit test that demonstrates that the fix works properly
> * Your tests are failing because the `.install_verilator.sh` seems out of date. I just pushed a new one to branch `master` you should be able to use that.
> * Just wanted to make sure that `release` is your intended target. `release` and `master` are diverging it would be nice to bring them back together, but I imagine that is beyond your scope.
> * Cheers

Hello chick. 

- I used the `release ` for pipeline design tests, I have not been encountered major problems with 3.886 verilator, the origin `.install_verilator.sh` can not work, I saw the newest `.install_verilator.sh` had been committed to `master`. 
- Sorry about I Pull request to `release` branch, and Indeed beyond my scope to merge `release` and `master`.

- Should I close this Pull request, and write some unit test and Pull a new patch request to `master`?. Thanks.

**Comment by chick** [comment]
- It's fine that you are using `release` that's probably what chipyard expects. I think .install_verilator.sh is only used for CI work. So you might want to add the changes to it in `master` to your `PR`. It would be nice to have the tests pass for any `PR` to be merged.
- I think `PR`ing against `release` is fine but I'd like to see `release` and `master` not get to far apart, but that's not on you to take that on.
- If you are too busy to work in a unit test that's ok, just say som but If you have time I think it would be good for you to add some simple unit test and just add the commit to this `PR`. I can review and merge.

**Comment by dhxsy1994** [comment]
Hi, Chick
- There have a problem of verilator version that I remember, the newest version of verilator can not run any riscv-mini tests, 
I spent a lot of time dealing with that error. so I think the patch for verilator on branch `master` should merge in `release`.  
- I committed a Unit test which name is `PipelineTests`. I use `LUI`, `AUIPC`, `JALR` instructions by two haven't been used generating functions `U` and `JR` to test, the test result it's ok.
- Thanks.

**Comment by dhxsy1994** [comment]
Hi, Chick
- There have a problem of verilator version that I remember, the newest version of verilator can not run any riscv-mini tests, 
I spent a lot of time dealing with that error. so I think the patch for verilator on branch `master` should merge in `release`.  
- I committed a Unit test which name is `PipelineTests`. I use `LUI`, `AUIPC`, `JALR` instructions by two haven't been used generating functions `U` and `JR` to test, the test result it's ok.
- Thanks.

**Pull request closed without merging**
